Develop2
zoec0110/rails pull request #2
Opened 2022-10-14 07:54 UTC by zoec0110

完成CRUD 應用程式

2022-10-14 15:45 UTC, hzchirs requested changes

2022-10-14 15:45 UTC, hzchirs commented on app/views/events/index.html.erb
> +  <%= link_to 'Delete', :controller => 'events', :action => 'destroy', :id => event %>
縮排要一致～

2022-10-14 15:45 UTC, hzchirs commented on app/views/events/edit.html.erb
> +<% end %>
縮排要一致，有的檔案空兩格、有的空四格，建議使用財報狗專案裡的 editorconfig 設定

2022-10-14 15:49 UTC, hzchirs commented
另外 commit 的目的性要很明確，且訊息要與內容相符
像是 `finish kaminari`
除了安裝 kaminari 外，還有檔案格式的調整 (Gemfile 的 " 改 ')、controller 的實做等

一個 commit 包含太多件事情，之後建議把 commit 顆粒差得更明確一些

舉例來說，finish kaminari 這個 commit 可以拆成數個 commit

- format Gemfile
- install gem: kaminari
- create EventsController
- ...etc

這樣在 Review 上會更明確

2022-10-17 09:58 UTC, hzchirs requested changes
新的 commit 整理得不錯 👍 

再把目前這個縮排修好就 ok 了

2022-10-17 09:58 UTC, hzchirs commented on app/views/events/new.html.erb
> +<%= f.submit "Create" %>
`do...end` 內的區塊也要縮排

2022-10-17 10:09 UTC, zoec0110 commented on app/views/events/new.html.erb
> +<%= f.submit "Create" %>
ok，沒問題
縮排已經修正

2022-10-17 10:20 UTC, hzchirs approved these changes

2022-10-17 10:22 UTC, merged